# abbr -a --position anywhere -- --help '--help | bat -plhelp'
# abbr -a --position anywhere -- -h '-h | bat -plhelp'
abbr cat "bat"
abbr ca "chezmoi apply" 
abbr cdc "cd ~/.local/share/chezmoi/"
abbr cf "chezmoi edit ~/.config/"
abbr cff "chezmoi edit ~/.config/fish/"
abbr cfh "chezmoi edit ~/.config/hypr/hyprland.conf"
abbr cft "chezmoi edit ~/.config/foot/foot.ini"
abbr cfv "chezmoi edit ~/.config/nvim/init.vim"
abbr cfw "chezmoi edit ~/.config/waybar/config"
abbr cfws "chezmoi edit ~/.config/waybar/style.css"
abbr e "emacs"
abbr g "git"
abbr ga "git add"
abbr gc "git commit -m"
abbr gd "git diff"
abbr gp "git push"
abbr gr "git remote set-url origin git@github.com:andrey-gusev/"
abbr gs "git status"
abbr man "batman"
abbr p "sudo pacman"
abbr sc "chezmoi edit ~/.local/bin/"
abbr sdn "shutdown now"
abbr sys "sudo systemctl"
abbr t "sudo tailscale"
abbr v "nvim"
abbr y "yay"
