general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl -r
    ignore_dbus_inhibit = false
}

# 1. Отключение подсветки клавиатуры (1 мин)
listener {
    timeout = 60
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# 2. Приглушение экрана (2.5 мин) — предупреждение перед отключением
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 3. МГНОВЕННОЕ отключение экрана + блокировка (3 мин)
listener {
    timeout = 180
    on-timeout = loginctl lock-session && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# 4. Переход в сон (5 мин)
listener {
    timeout = 300
    on-timeout = systemctl suspend
}
