background {
    color = black
}

label {
    color = white
    text = $TIME
    font_size = 90
    font_family = FiraCode Nerd Font
    halign = center
    valign = center
    fail_timeout = 0
}

label {
    fail_text = "Wrong pass!"
    halign = center
    valign = center
    position = 0, 150
    visible = $FAILED
}

label {
    text = $LAYOUT
    halign = right
    valign = bottom
}
